service: function

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: eu-north-1
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  demo:
    timeout: 900
    memorySize: 2048
    image:
      name: img
